services:
  eureka-server:
    image: eurekaserver:latest
    container_name: ms-eureka-server
    build:
      context: ../ms-eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - bank-network

  config-server:
    image: configserver:latest
    container_name: config-server
    build:
      context: ../config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - bank-network

  api-gateway:
    image: apigateway:latest
    container_name: api-gateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - config-server
    networks:
      - bank-network

  ms-authentication:
    image: ms-authentication:latest
    container_name: ms-authentication
    build:
      context: ../ms-authentication
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    depends_on:
      - eureka-server
      - config-server
    networks:
      - bank-network

  ms-customer:
    image: ms-customer:latest
    container_name: ms-customer
    build:
      context: ../ms-customer
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - config-server
    networks:
      - bank-network

  ms-account:
    image: ms-account:latest
    container_name: ms-account
    build:
      context: ../ms-accounts
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - config-server
    networks:
      - bank-network

  ms-credit:
    image: ms-credit:latest
    container_name: ms-credit
    build:
      context: ../ms-credits
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - config-server
    networks:
      - bank-network

  ms-transactions:
    image: ms-transactions:latest
    container_name: ms-transactions
    build:
      context: ../ms-transactions
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - config-server
    networks:
      - bank-network

networks:
  bank-network:
    driver: bridge
